### ISSUE TITLE
If this is deprecated what's the replacement?

### ISSUE THREAD

**Issue by ghost** [janestreet/async_parallel#3]
The module has been renamed to `Async_parallel_deprecated` ... what's the non-deprecated version that's meant to be used?

**Comment by bmillwood** [comment]
https://github.com/janestreet/rpc_parallel is what we use for doing parallel process management these days.

It's not a drop-in replacement. It can't be, because the async_parallel API is a little bit too permissive in terms of letting you transmit things over the wire that don't necessarily have sensible serialization (like lazy values or functions) and the process architecture was a bit too magic and confusing.

But it should be capable of solving the same problems at a high level.
